name: admob_kit_example
description: Minimal usage example for admob_kit.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  admob_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
